### ISSUE TITLE
Помечать в списке over-verification таски

### ISSUE THREAD

**Issue by MichaelTheLi** [xcart/prognosis-app#48]
Таски в over-verification сбивают с толку - загрузка на день становится неадекватная и внезапная.
Их либо помечать, что они требуют действия,  либо иначе считать в загрузке.
Таска **MMY Filter**, как пример.
До наступления verification
<img width="828" alt="Screenshot 2020-12-01 at 13 54 06" src="https://user-images.githubusercontent.com/2879949/100724806-b8222800-33dc-11eb-883d-10be4fdc7c89.png">

После наступления verification
<img width="804" alt="Screenshot 2020-12-01 at 13 53 50" src="https://user-images.githubusercontent.com/2879949/100724798-b5bfce00-33dc-11eb-8be1-79851f507f1b.png">

**Comment by drdaemos** [comment]
Пофикшено
